export const easingMap: { [key: string]: string } = {
  Linear: "linear",
  EaseIn: "inQuad",
  EaseOut: "outQuad",
  EaseInOut: "inOutQuad",
  BackEaseIn: "inBack",
  BackEaseOut: "outBack",
  BackEaseInOut: "inOutBack",
  BounceEaseIn: "inBounce",
  BounceEaseOut: "outBounce",
  BounceEaseInOut: "inOutBounce",
  StrongEaseIn: "inQuart",
  StrongEaseOut: "outQuart",
  StrongEaseInOut: "inOutQuart",
};
